name: Physt

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - os: windows-latest
            python: "3.10"

          - os: macos-latest
            python: "3.10"


    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[dev,dask,pandas,xarray,matplotlib,plotly,vega3,folium,root,xtermcolor]

      - name: Run pytest
        run: pytest

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[dev,dask,pandas,xarray,matplotlib,plotly,vega3,folium,root,xtermcolor]

      - name: Run mypy (on source)
        run: mypy src/physt

      - name: Run mypy (on tests)
        run: mypy tests

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build
        run: python -m build
