name: Physt

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: windows-latest
            python: 3.9

          - os: macos-latest
            python: 3.9


    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[dev,dask,pandas,xarray,matplotlib,plotly,vega3,folium,root,xtermcolor]

      - name: Run pytest
        run: pytest

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[dev,dask,pandas,xarray,matplotlib,plotly,vega3,folium,root,xtermcolor]

      - name: Run mypy (on source)
        run: mypy code/physt

      - name: Run mypy (on tests)
        run: mypy tests
